from .dashboard_views import *
from .schedule_views import *
from .export_views import *
from .auth_views import *
from .teacher_views import *
from .department_views import *
from .section_views import *
from .level_views import *
from .room_views import *
from .subject_views import *
from .chief_views import *
from .academic_views import *