# Generated by Django 5.2.7 on 2026-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_type',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course_type',
            field=models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques')], default='CM', max_length=10),
        ),
    ]
